package fcm

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// ClientMock implements Client
type ClientMock struct {
	t minimock.Tester

	funcSend          func(ctx context.Context, msg *Message) (rp1 *Response, err error)
	inspectFuncSend   func(ctx context.Context, msg *Message)
	afterSendCounter  uint64
	beforeSendCounter uint64
	SendMock          mClientMockSend
}

// NewClientMock returns a mock for Client
func NewClientMock(t minimock.Tester) *ClientMock {
	m := &ClientMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SendMock = mClientMockSend{mock: m}
	m.SendMock.callArgs = []*ClientMockSendParams{}

	return m
}

type mClientMockSend struct {
	mock               *ClientMock
	defaultExpectation *ClientMockSendExpectation
	expectations       []*ClientMockSendExpectation

	callArgs []*ClientMockSendParams
	mutex    sync.RWMutex
}

// ClientMockSendExpectation specifies expectation struct of the Client.Send
type ClientMockSendExpectation struct {
	mock    *ClientMock
	params  *ClientMockSendParams
	results *ClientMockSendResults
	Counter uint64
}

// ClientMockSendParams contains parameters of the Client.Send
type ClientMockSendParams struct {
	ctx context.Context
	msg *Message
}

// ClientMockSendResults contains results of the Client.Send
type ClientMockSendResults struct {
	rp1 *Response
	err error
}

// Expect sets up expected params for Client.Send
func (mmSend *mClientMockSend) Expect(ctx context.Context, msg *Message) *mClientMockSend {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("ClientMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &ClientMockSendExpectation{}
	}

	mmSend.defaultExpectation.params = &ClientMockSendParams{ctx, msg}
	for _, e := range mmSend.expectations {
		if minimock.Equal(e.params, mmSend.defaultExpectation.params) {
			mmSend.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSend.defaultExpectation.params)
		}
	}

	return mmSend
}

// Inspect accepts an inspector function that has same arguments as the Client.Send
func (mmSend *mClientMockSend) Inspect(f func(ctx context.Context, msg *Message)) *mClientMockSend {
	if mmSend.mock.inspectFuncSend != nil {
		mmSend.mock.t.Fatalf("Inspect function is already set for ClientMock.Send")
	}

	mmSend.mock.inspectFuncSend = f

	return mmSend
}

// Return sets up results that will be returned by Client.Send
func (mmSend *mClientMockSend) Return(rp1 *Response, err error) *ClientMock {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("ClientMock.Send mock is already set by Set")
	}

	if mmSend.defaultExpectation == nil {
		mmSend.defaultExpectation = &ClientMockSendExpectation{mock: mmSend.mock}
	}
	mmSend.defaultExpectation.results = &ClientMockSendResults{rp1, err}
	return mmSend.mock
}

//Set uses given function f to mock the Client.Send method
func (mmSend *mClientMockSend) Set(f func(ctx context.Context, msg *Message) (rp1 *Response, err error)) *ClientMock {
	if mmSend.defaultExpectation != nil {
		mmSend.mock.t.Fatalf("Default expectation is already set for the Client.Send method")
	}

	if len(mmSend.expectations) > 0 {
		mmSend.mock.t.Fatalf("Some expectations are already set for the Client.Send method")
	}

	mmSend.mock.funcSend = f
	return mmSend.mock
}

// When sets expectation for the Client.Send which will trigger the result defined by the following
// Then helper
func (mmSend *mClientMockSend) When(ctx context.Context, msg *Message) *ClientMockSendExpectation {
	if mmSend.mock.funcSend != nil {
		mmSend.mock.t.Fatalf("ClientMock.Send mock is already set by Set")
	}

	expectation := &ClientMockSendExpectation{
		mock:   mmSend.mock,
		params: &ClientMockSendParams{ctx, msg},
	}
	mmSend.expectations = append(mmSend.expectations, expectation)
	return expectation
}

// Then sets up Client.Send return parameters for the expectation previously defined by the When method
func (e *ClientMockSendExpectation) Then(rp1 *Response, err error) *ClientMock {
	e.results = &ClientMockSendResults{rp1, err}
	return e.mock
}

// Send implements Client
func (mmSend *ClientMock) Send(ctx context.Context, msg *Message) (rp1 *Response, err error) {
	mm_atomic.AddUint64(&mmSend.beforeSendCounter, 1)
	defer mm_atomic.AddUint64(&mmSend.afterSendCounter, 1)

	if mmSend.inspectFuncSend != nil {
		mmSend.inspectFuncSend(ctx, msg)
	}

	mm_params := &ClientMockSendParams{ctx, msg}

	// Record call args
	mmSend.SendMock.mutex.Lock()
	mmSend.SendMock.callArgs = append(mmSend.SendMock.callArgs, mm_params)
	mmSend.SendMock.mutex.Unlock()

	for _, e := range mmSend.SendMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.rp1, e.results.err
		}
	}

	if mmSend.SendMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSend.SendMock.defaultExpectation.Counter, 1)
		mm_want := mmSend.SendMock.defaultExpectation.params
		mm_got := ClientMockSendParams{ctx, msg}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSend.t.Errorf("ClientMock.Send got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSend.SendMock.defaultExpectation.results
		if mm_results == nil {
			mmSend.t.Fatal("No results are set for the ClientMock.Send")
		}
		return (*mm_results).rp1, (*mm_results).err
	}
	if mmSend.funcSend != nil {
		return mmSend.funcSend(ctx, msg)
	}
	mmSend.t.Fatalf("Unexpected call to ClientMock.Send. %v %v", ctx, msg)
	return
}

// SendAfterCounter returns a count of finished ClientMock.Send invocations
func (mmSend *ClientMock) SendAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSend.afterSendCounter)
}

// SendBeforeCounter returns a count of ClientMock.Send invocations
func (mmSend *ClientMock) SendBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSend.beforeSendCounter)
}

// Calls returns a list of arguments used in each call to ClientMock.Send.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSend *mClientMockSend) Calls() []*ClientMockSendParams {
	mmSend.mutex.RLock()

	argCopy := make([]*ClientMockSendParams, len(mmSend.callArgs))
	copy(argCopy, mmSend.callArgs)

	mmSend.mutex.RUnlock()

	return argCopy
}

// MinimockSendDone returns true if the count of the Send invocations corresponds
// the number of defined expectations
func (m *ClientMock) MinimockSendDone() bool {
	for _, e := range m.SendMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SendMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSendCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSend != nil && mm_atomic.LoadUint64(&m.afterSendCounter) < 1 {
		return false
	}
	return true
}

// MinimockSendInspect logs each unmet expectation
func (m *ClientMock) MinimockSendInspect() {
	for _, e := range m.SendMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to ClientMock.Send with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SendMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSendCounter) < 1 {
		if m.SendMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to ClientMock.Send")
		} else {
			m.t.Errorf("Expected call to ClientMock.Send with params: %#v", *m.SendMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSend != nil && mm_atomic.LoadUint64(&m.afterSendCounter) < 1 {
		m.t.Error("Expected call to ClientMock.Send")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *ClientMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockSendInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *ClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *ClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSendDone()
}
